//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.09.29 at 12:23:01 AM UTC
//


package com.todoapp.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.todoapp.ws package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.todoapp.ws
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoginRequest }
     *
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     *
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetTodosRequest }
     *
     */
    public GetTodosRequest createGetTodosRequest() {
        return new GetTodosRequest();
    }

    /**
     * Create an instance of {@link GetTodosResponse }
     *
     */
    public GetTodosResponse createGetTodosResponse() {
        return new GetTodosResponse();
    }

    /**
     * Create an instance of {@link Todo }
     *
     */
    public Todo createTodo() {
        return new Todo();
    }

    /**
     * Create an instance of {@link AddTodoRequest }
     *
     */
    public AddTodoRequest createAddTodoRequest() {
        return new AddTodoRequest();
    }

    /**
     * Create an instance of {@link AddTodoResponse }
     *
     */
    public AddTodoResponse createAddTodoResponse() {
        return new AddTodoResponse();
    }

    /**
     * Create an instance of {@link UpdateTodoRequest }
     *
     */
    public UpdateTodoRequest createUpdateTodoRequest() {
        return new UpdateTodoRequest();
    }

    /**
     * Create an instance of {@link UpdateTodoResponse }
     *
     */
    public UpdateTodoResponse createUpdateTodoResponse() {
        return new UpdateTodoResponse();
    }

    /**
     * Create an instance of {@link DeleteTodoRequest }
     *
     */
    public DeleteTodoRequest createDeleteTodoRequest() {
        return new DeleteTodoRequest();
    }

    /**
     * Create an instance of {@link DeleteTodoResponse }
     *
     */
    public DeleteTodoResponse createDeleteTodoResponse() {
        return new DeleteTodoResponse();
    }

}
