//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.09.28 at 06:39:17 PM UTC
//


package com.todoapp.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for todo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="todo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="done" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "todo", propOrder = {
    "id",
    "task",
    "done"
})
public class Todo {

    protected int id;
    @XmlElement(required = true)
    protected String task;
    protected boolean done;

    /**
     * Gets the value of the id property.
     *
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the task property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTask() {
        return task;
    }

    /**
     * Sets the value of the task property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTask(String value) {
        this.task = value;
    }

    /**
     * Gets the value of the done property.
     *
     */
    public boolean isDone() {
        return done;
    }

    /**
     * Sets the value of the done property.
     *
     */
    public void setDone(boolean value) {
        this.done = value;
    }

}
